name: clip
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.8.5
  - pip=22.3.1
  - cudatoolkit=11.7
  - ipykernel
  - jupyter
  - pip:
      - torch==2.0.0
      - torchvision==0.15.1
      - ftfy
      - regex
      - tqdm
      - git+https://github.com/openai/CLIP.git
      - matplotlib
      - seaborn
      - pandas
      - numpy
      - pillow
